version: '2'
services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - ./workspace:/home/jekyll
    working_dir: /srv/jekyll
    command: jekyll serve -s /home/jekyll --watch --incremental
    ports:
      - "4000:4000"
